### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by pawlyk** [RafeKettler/magicmethods#50]
You missed described next() for python 2.* and __next__() for python 3.*. This is important methods for iterator protocol.

**Comment by RafeKettler** [comment]
Thanks for the report! If I get around to writing a new version of this document for py3, I will be sure to document `__next__`. For Python 2, it doesn't fall under the umbrella of magic methods because it doesn't control any builtins. I think the iterator protocol is well documented by https://docs.python.org/2/library/stdtypes.html#iterator-types, but it would not hurt to have a pointer to those docs in http://rafekettler.com/magicmethods.html#sequence.
